### ISSUE TITLE
[Fix] docs.immudb.io has no updated SDK compatibility

### ISSUE THREAD

**Issue by tomekkolo** [codenotary/immudb.io#185]
![Image](https://user-images.githubusercontent.com/38069337/186259558-d8f463da-661e-4539-ae76-749c72554923.png)

**Comment by tomekkolo** [comment]
Please also add this as a part of release process (either manual or automatic).

**Comment by emkaminsk** [comment]
To discuss if there should be a separate table per SDK.
Most recent SDK version, minimum compatible immudb version.
