### ISSUE TITLE
Update algolia logo url

### ISSUE THREAD

**Issue by tomekkolo** [codenotary/immudb.io#197]

**Comment by zatkniz** [comment]
Unfortunately, I failed trying to fix this issue for the following reasons: 

1) https://docsearch.algolia.com/docs/api#hitcomponent as described here if you want to overwrite the dropdown list you need to render a JSX element. In vue this is something that is possible but everything that I tried seems like it is not working. The most basic usage throws error as described here https://vuejs.org/guide/extras/render-function.html#creating-vnodes

2) Seems like the algolia icon irl is the correct one.
