### ISSUE TITLE
Update dependencies for immudb.io

### ISSUE THREAD

**Issue by tomekkolo** [codenotary/immudb.io#223]
https://github.com/codenotary/immudb.io/security/dependabot

**Comment by emkaminsk** [comment]
@iams - @arriqaaq is also working on it, but the golang part.

**Comment by emkaminsk** [comment]
Is it this one? https://github.com/codenotary/immudb.io/pull/338

**Comment by iamvs** [comment]
@emkaminsk - yup, but some tests still failing, going to investigate that.

**Comment by tomekkolo** [comment]
moving back to backlog as we are going to move to docusaurus with docs.
