### ISSUE TITLE
Versions dropdown got transparent bg

### ISSUE THREAD

**Issue by dxps** [codenotary/immudb.io#57]
This issue got introduced recently.

![image](https://user-images.githubusercontent.com/14140226/109634233-ac680e00-7b51-11eb-9e39-9d260e802319.png)

**Comment by Hextar** [comment]
Fixed with:
https://github.com/codenotary/immudb.io/commit/c530dcfa05afaf6b015e967a7329618e4c61b2a8

**Comment by dxps** [comment]
Closing it since this was just an intermediate (during an update) state.

End result is way better than before:
![image](https://user-images.githubusercontent.com/14140226/109635012-8db64700-7b52-11eb-8a88-5a27735c9fc4.png)
